### ISSUE TITLE
How can I use it with lazy module?

### ISSUE THREAD

**Issue by clegeard** [tinesoft/ngx-scrollreveal#83]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X ] feature request
```

### Mention any other details that might be useful

Hi,
I just wanted to know how to install the module for lazy modules. It seems to work otherwise but when I use it in Lazy Modules, the dom elements I try to animate remain hidden with opacity 0. I can't see any error in the console.
I tried to add .forRoot() to the import but I got the error saying that this property does not exist.
I hope you can help.
Thanks

Christele

**Comment by clegeard** [comment]
I managed to fix my problem.

**Comment by tinesoft** [comment]
Hi,

I'm glad you fix your problem, sorry I didn't have time to help...

Can you elaborate how you did? (for future readers)
