### ISSUE TITLE
Is this ngx-scrollreveal is free for commercial use ?

### ISSUE THREAD

**Issue by Nitekurs** [tinesoft/ngx-scrollreveal#91]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

**Comment by tinesoft** [comment]
Hi @Nitekurs ,

`ngx-scrollreveal` (A.K.A this library) is under [MIT License](https://github.com/tinesoft/ngx-scrollreveal/blob/master/LICENSE), so free for commercial use.

But it is merely an Angular warpper to `scrollreveal` (the  core library underneath, which actually does ALL the work ), and the latter **now requires a commercial license starting v4.x.x**(see this [post](https://github.com/scrollreveal/scrollreveal/issues/345#issuecomment-322192286) from its author)

So yes, you'll need to purchase a license for commercial use.

Please have a look at https://scrollrevealjs.org/pricing/ for more info
